network_name: "net-{{ cluster_name }}"
path_base_dir: /home/redhat
vm_create_scripts_dir: "{{ path_base_dir }}/vm_create_scripts/"
qemu_user: "{{ ansible_user | default(ansible_env.USER) }}"

virt_packages:
  - python3
  - libvirt
  - virt-install
  - qemu-kvm
  - virt-manager
  - python3-pip
  - python3-lxml
  - python3-libvirt

images_dir: /var/lib/libvirt/images/

is_on_rhel9: "{{ (ansible_distribution_major_version == '9' and ansible_distribution == 'RedHat') | bool }}"

# allowed modes: 'bridge', 'nat', using 'bridge' as default
create_vms_network_mode: bridge

# define additional networks: a list of dictionaries with name, mode and bridge_name
create_vms_additional_networks: []
# Example:
# create_vms_additional_networks:
#   - name: "net-{{ cluster_name }}-mgmt"
#     mode: bridge
#     bridge_name: virbr1
#     cidr: 192.168.100.0/24  # only needed for nat mode

# disable secure boot, false by default
create_vms_disable_secure_boot: false

# Default OVMF_CODE path.
# This should be a symlink to `/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd`
create_vms_x86_64_ovmf_code_path: "/usr/share/OVMF/OVMF_CODE.secboot.fd"

# Path to default OVMF_VARS.fd file used for non secure boot
create_vms_non_secure_ovmf_vars_path: /usr/share/edk2/ovmf/OVMF_VARS.fd

# Path to default OVMF_VARS.fd file used for secure boot
create_vms_secure_ovmf_vars_path: /usr/share/edk2/ovmf/OVMF_VARS.secboot.fd
