- name: Setup network
  become: true
  block:
    - name: Check if the selected network mode is allowed
      vars:
        allowed_vm_network_modes:
          - bridge
          - nat
      assert:
        that:
          - create_vms_network_mode in allowed_vm_network_modes
        fail_msg: "{{ create_vms_network_mode }} is not a supported network mode"

    # Process all networks (default + additional) using create_vms_networks
    - name: Define networks
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'network.xml.j2') }}"
      loop: "{{ create_vms_networks }}"

    - name: Start networks
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        command: start
      loop: "{{ create_vms_networks }}"
